name: CI/CD Pipeline

on:
  push:
    branches:
      - main 
      - development
      - feature/*
    tags:
      - 'v*'
  pull_request:
    branches:
      - main
      - development
      - feature/*
    types: [ closed ]

jobs:
  # Job 1: Test Job
  test-development-stage:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Run tests
        run: |
          echo "Running tests..."

  # Job 2: Deploy to Development (Test environment)
  deploy-to-dev:
    runs-on: ubuntu-latest
    needs: test-development-stage
#    if: github.event_name == 'push' && github.ref == 'refs/heads/development'
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Development environment
        run: |
          echo "Deploying to Development environment"
